### PR TITLE
Delay appearance of progress bar

### PR DESCRIPTION
**Pull request by aaronshaf**

### CODE REVIEW

**Comment by jor3l** [comment]
If the load is less than 2s, this means we will see a white screen for a while and then the resource?

**Comment by aaronshaf** [comment]
Yes

**Comment by jor3l** [comment]
shouldn't we have something to let the user know is loading? I think for the UX this is bad

**Comment by aaronshaf** [comment]
If it's a small cartridge (which will often be the case) they will get only a quick flash of a loading indicator, which isn't useful. Delaying a loading indicator is a [common practice](https://www.smashingmagazine.com/2016/12/best-practices-for-animated-progress-indicators/).

**Comment by aaronshaf** [comment]
Decreased it to 1s

**Pull request merged**
