### PR TITLE
Allow iframe tag in rich content

### PR DESCRIPTION
**Pull request by aaronshaf**
Fixes CM-673

### CODE REVIEW

**Comment by aaronshaf** [comment]
Any ideas what the title should be? These iframes come from user-supplied rich content.

**Comment by cguanzon** [comment]
> Any ideas what the title should be? These iframes come from user-supplied rich content.

@aaronshaf "External Content" could work

**Comment by aaronshaf** [comment]
iframe in this case is user-supplied

**Comment by cguanzon** [comment]
iframe is not in our control

**Pull request merged**
