### PR TITLE
Rubrics for assignments

### PR DESCRIPTION
**Pull request by jor3l**
This branch adds support to the assignments to show its rubric. 

fixes CM-414

### CODE REVIEW

**Comment by jor3l** [comment]
@cguanzon possible solution is to use a table with fixed layout, the problem is that it looks a bit weird 
image compared to what we have now 
image

**Comment by cguanzon** [comment]
> @cguanzon possible solution is to use a table with fixed layout, the problem is that it looks a bit weird
> image compared to what we have now
> image

@jor3l can you show this to kdub?

**Comment by cguanzon** [comment]
needs rebase

**Comment by jor3l** [comment]
Moving to new branch

**Pull request closed without merging**
