### PR TITLE
Fix: Make regular assignments viewable

### PR DESCRIPTION
**Pull request by RobertDHanna**
Note:
 - This problem is a result of a bug where assignments are exported
   as associated content if the course is exported through Canvas.
   Assignments are correctly exported as assignments if the course imscc
   is downloaded through Commons. A ticket will be filed notifying Canvas
   of this problem.

Test Plan:
 - Export a course with assignments through Canvas.
 - The assignments do not show up as unidentified.
 - Clicking on an assignment shows its information.
 - The assignments list contains all of the course assignments.

fixes CM-549

### CODE REVIEW

**Comment by aaronshaf** [comment]
Please delay merge until my CM-500 commit is in. Lots of `entryMap` conflict forthcoming.

**Comment by RobertDHanna** [comment]
Refactored the code to include only 1 /assignments route.

**Comment by RobertDHanna** [comment]
Filed Jira Ticket https://instructure.atlassian.net/browse/CNVS-44558

**Comment by RobertDHanna** [comment]
Absolutely, Caleb. The plan was to add the specs after Aaron's commit is merged (add already-extracted local imscc data for tests), but if you would rather have me add the tests now just so we have them I am happy to do that.

**Comment by aaronshaf** [comment]
Needs rebase now. No files others than CommonCartridge.js should have reference to `entryMap`. See new paradigm in 6d623c0b447d982fce461854612a05b2e2e32d6c, especially `this.props.getTextByPath`

**Comment by RobertDHanna** [comment]
Rebased & refactored code to stop relying on `entryMap`.

**Pull request merged**
